#!/usr/bin/env bash

set -uexo pipefail

# Files

cp -arfT files/etc /etc

if [ "$xiaomi_nabu_samsung_ufs" = "true" ]; then
    cp -arfT files/samsung/etc /etc
fi

# Packages

dnf -y install \
    xiaomi-nabu-firmware \
    alsa-ucm-conf-sm8150 \
    ath10k-shutdown \
    tqftpserv \
    qbootctl \
    rmtfs \
    qrtr

# Services

systemctl enable \
    tqftpserv.service \
    rmtfs.service \
    qbootctl.service

# Kernel

mkdir -p /boot/dtb
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core \
    kernel-headers
rm -rf /usr/lib/modules/*
dnf -y install kernel
rm -r /boot/dtb
