#!/usr/bin/env bash

set -uexo pipefail

cp -arfT files/etc /etc

# packages
dnf -y remove alsa-ucm # conflicts with alsa-ucm-conf-qcom-sc7280
dnf -y install \
    nothing-spacewar-firmware \
    alsa-ucm-conf-qcom-sc7280 \
    tqftpserv \
    qbootctl \
    rmtfs \
    qrtr

# kernel
mkdir -p /boot/dtb
dnf -y remove \
    kernel \
    kernel-core \
    kernel-modules \
    kernel-modules-core \
    kernel-headers
dnf -y install kernel
rm -r /boot/dtb

# services
systemctl enable \
    tqftpserv.service \
    qbootctl.service \
    rmtfs.service
