#!/usr/bin/env bash

set -uexo pipefail

cp -arfT files/etc /etc
cp -arfT files/usr /usr

# workaround (see https://github.com/ublue-os/bluefin-lts/issues/3)
mkdir -p /var/roothome

# setup development tools
dnf -y install git just buildah
systemctl enable sshd.service

# usb network
dnf -y install usb-network
systemctl enable usb-network.service

# only keep the EN langpack to decrease image size
dnf -y swap glibc-all-langpacks glibc-langpack-en

dnf -y remove dracut-config-rescue

dnf -y remove nvidia-gpu-firmware

# bluetooth is broken after 5.85
# since 5.85 is not available on f44 branch, `|| true` is required
dnf -y downgrade bluez-5.85 || true
dnf -y versionlock add bluez
